import { useStore } from '../store';
import { differenceInDays, parseISO } from 'date-fns';
import { useMemo } from 'react';

export default function Reports() {
  const { payments, chargeItems, reservations, vehicles } = useStore();

  const metrics = useMemo(() => {
    // Collect all standard payments
    const standardPayments = payments.filter(p => p.type === 'payment');
    
    // Total standard revenue
    const totalStandardRevenue = standardPayments.reduce((sum, p) => sum + p.amount, 0);

    // Calculate revenue based on proportion.
    // To strictly assign actual payment revenue, we can look at paid charges. 
    // Another approach is just taking the paid charges as revenue. 
    // Let's use paid charge amounts directly to represent revenue generated by category.
    const paidCharges = chargeItems.filter(c => c.paymentStatus === 'Paid');
    const fineRevenue = paidCharges.filter(c => c.category === 'Fine').reduce((sum, c) => sum + c.amount, 0);
    const claimRevenue = paidCharges.filter(c => c.category === 'Claim').reduce((sum, c) => sum + c.amount, 0);
    const externalRevenue = paidCharges.filter(c => c.category === 'External Charge').reduce((sum, c) => sum + c.amount, 0);
    const switchRevenue = paidCharges.filter(c => c.category === 'Vehicle Switch').reduce((sum, c) => sum + c.amount, 0);
    
    // Rental Revenue is base rental of paid-up reservations, or general payments minus paid charges.
    // For simplicity: Rental Revenue calculation = Total Payments - (Fines + Claims + External + Switch)
    const optionalChargesRevenue = fineRevenue + claimRevenue + externalRevenue + switchRevenue;
    const rentalRevenue = Math.max(0, totalStandardRevenue - optionalChargesRevenue);

    // Deposit revenue must be 0
    const depositRevenue = 0;

    return {
      total: totalStandardRevenue,
      rentalRevenue,
      fineRevenue,
      claimRevenue,
      externalRevenue,
      switchRevenue,
      depositRevenue
    };
  }, [payments, chargeItems]);

  const utilization = useMemo(() => {
    return vehicles.map(v => {
      // Find completed or active reservations extending over this period.
      // For a simple metric, we'll calculate historical days rented all-time
      const vehicleReservations = reservations.filter(r => r.vehicleId === v.id && !['Cancelled', 'Pending'].includes(r.status));
      
      let daysRented = 0;
      let vehicleRevenue = 0;

      vehicleReservations.forEach(r => {
        let days = differenceInDays(parseISO(r.returnDate), parseISO(r.pickupDate));
        if (days < 1) days = 1;
        daysRented += days;
        
        // Sum basic revenue associated with this vehicle
        // Calculate amount paid specifically for this reservation
        const resPayments = payments.filter(p => p.reservationId === r.id && p.type === 'payment').reduce((sum, p) => sum + p.amount, 0);
        vehicleRevenue += resPayments;
      });

      // Assuming an arbitrary total fleet lifetime (e.g. 365 days for the prototype, or just based on first booking)
      // We will do a generic utilization score based on an arbitrary 30-day window for simplicity in this demo
      const utilizationPercent = Math.min(100, Math.round((daysRented / 30) * 100));

      return {
        ...v,
        daysRented,
        vehicleRevenue,
        utilizationPercent
      };
    }).sort((a, b) => b.vehicleRevenue - a.vehicleRevenue);
  }, [vehicles, reservations, payments]);

  return (
    <div className="space-y-6">
      <h2 className="text-2xl font-bold tracking-tight text-gray-900">Reports Array</h2>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="bg-white border border-gray-100 rounded-xl shadow-sm p-6 space-y-4">
          <h3 className="font-bold text-lg text-gray-900 border-b pb-2">Revenue Breakdowns</h3>
          
          <div className="space-y-3">
            <div className="flex justify-between items-center text-sm">
              <span className="text-gray-600">Rental Revenue</span>
              <span className="font-medium text-gray-900">${metrics.rentalRevenue.toFixed(2)}</span>
            </div>
            <div className="flex justify-between items-center text-sm">
              <span className="text-gray-600">Fine Revenue</span>
              <span className="font-medium text-gray-900">${metrics.fineRevenue.toFixed(2)}</span>
            </div>
            <div className="flex justify-between items-center text-sm">
              <span className="text-gray-600">Claim Revenue</span>
              <span className="font-medium text-gray-900">${metrics.claimRevenue.toFixed(2)}</span>
            </div>
            <div className="flex justify-between items-center text-sm">
              <span className="text-gray-600">External Charge Revenue</span>
              <span className="font-medium text-gray-900">${metrics.externalRevenue.toFixed(2)}</span>
            </div>
            <div className="flex justify-between items-center text-sm">
              <span className="text-gray-600">Vehicle Switch Revenue</span>
              <span className="font-medium text-gray-900">${metrics.switchRevenue.toFixed(2)}</span>
            </div>
            <div className="flex justify-between items-center text-sm pt-2 border-t font-semibold">
              <span className="text-gray-900">Deposit Revenue</span>
              <span className="text-gray-900">${metrics.depositRevenue.toFixed(2)}</span>
            </div>
          </div>
          
          <div className="bg-green-50 p-4 rounded-lg mt-4 flex justify-between items-center">
            <span className="font-bold text-green-800">Total Recognized Revenue</span>
            <span className="font-bold text-green-800 text-xl">${metrics.total.toFixed(2)}</span>
          </div>
        </div>

        <div className="bg-white border border-gray-100 rounded-xl shadow-sm overflow-hidden flex flex-col">
          <div className="p-6 border-b border-gray-100">
            <h3 className="font-bold text-lg text-gray-900">Fleet Utilization</h3>
            <p className="text-xs text-gray-500 mt-1">Based on estimated 30-day trailing metric</p>
          </div>
          <div className="flex-1 overflow-auto">
            <table className="w-full text-left text-sm whitespace-nowrap">
              <thead className="bg-gray-50 text-gray-500 font-medium border-b border-gray-100">
                <tr>
                  <th className="px-6 py-3">Vehicle</th>
                  <th className="px-6 py-3 text-right">Days Rented</th>
                  <th className="px-6 py-3 text-right">Revenue</th>
                  <th className="px-6 py-3 text-right">Utilization</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100">
                {utilization.map(v => (
                  <tr key={v.id} className="hover:bg-gray-50">
                    <td className="px-6 py-4 font-medium text-gray-900">{v.year} {v.make} {v.model}</td>
                    <td className="px-6 py-4 text-right">{v.daysRented}d</td>
                    <td className="px-6 py-4 text-right text-green-600 font-medium">${v.vehicleRevenue.toFixed(2)}</td>
                    <td className="px-6 py-4 text-right">
                      <div className="flex flex-col items-end">
                        <span>{v.utilizationPercent}%</span>
                        <div className="w-16 h-1.5 bg-gray-200 rounded-full mt-1 overflow-hidden">
                          <div className="bg-indigo-500 h-full" style={{width: `${Math.min(100, v.utilizationPercent)}%`}}></div>
                        </div>
                      </div>
                    </td>
                  </tr>
                ))}
                {utilization.length === 0 && (
                  <tr>
                    <td colSpan={4} className="px-6 py-8 text-center text-gray-500">No vehicles tracked.</td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
}
